### ISSUE TITLE
총이 없을 때 앉기를 하면 모션은 바뀌지 않지만 이동 속도는 감소하는 문제

### ISSUE THREAD

**Issue by Seobok** [SR-PLUM/SolRising#49]
총이 없을 때 앉기를 하면 모션은 바뀌지 않지만 이동 속도는 감소하는 문제

**Comment by ehdrud0122** [comment]
모션을 찾거나 총이 없으면 return

**Comment by ehdrud0122** [comment]
https://github.com/SR-PLUM/SolRising/pull/53/commits/806ef8e20d180cf16730cea9bb1cb15d8ddbf977
